/* global module:true */
module.exports = function(grunt) {
    "use strict";

    grunt.initConfig({
        // require js optimization
        requirejs: {
            compile: {
                options: {
                    // name is required
                    name: "todo-main",
                    // the base path of our optimization
                    baseUrl: "public/js/todo",
                    // include almond to get define (in place of require.js)
                    include: "../lib/almond-0.2.5",
                    // use our original main configuration file to avoid
                    // duplication.  this file will pull in all our dependencies
                    mainConfigFile: "public/js/todo/todo-main.js",
                    // the output optimized file name
                    out: "public/js/todo/todo-min.js"
                }
            }
        },
        // CSS minify
        cssmin: {
            add_banner: {
                options: {
                    // adds this banner to the minified output
                    banner: "/* Simple Todo minified CSS */"
                },
                // minify all files found in the CSS directory
                // to a single output file
                files: {
                    "public/css/todo-app.min.css": ["public/css/**/*.css"]
                }
            }
        }
    });

    // load the tasks we've utilized within this config
    grunt.loadNpmTasks("grunt-contrib-requirejs");
    grunt.loadNpmTasks('grunt-contrib-cssmin');

    // define the default (no arg) task to run requirejs and cssmin
    grunt.registerTask("default", ["requirejs", "cssmin"]);

    // Helper task to clean up generated code
    grunt.registerTask("clean", function() {
        // delete our todo-min.js generated by requirejs optimization
        grunt.file.delete("public/js/todo/todo-min.js");
        // and delete our todo-app.min.css, generated by cssmin
        grunt.file.delete("public/css/todo-app.min.css");
    });
};